### PR TITLE
Fix Lizard collision handling

### LINKED ISSUE #72: Faulty colision handling for same lane overtake situations with front player using LIZARD
Please refer [to this forum discusion](https://forum.entelect.co.za/t/same-lane-overtake-with-front-player-using-lizard-jump/1019)

It seems there might have been a copy-paste error with colision detection when lizard status is involved.
See [here](https://github.com/EntelectChallenge/2020-Overdrive/blob/4d5e2ac061ac3219311a6a12253a47be1ab51f78/game-engine/src/main/scala/za/co/entelect/challenge/game/contracts/map/CarGameMap.scala#L212)

### PR DESCRIPTION
**Pull request by ThePheonixGuy**
Closes #72

### CODE REVIEW

File: game-engine/src/test/scala/Command_Use_Lizard_Tests.scala [hunk 1]
```diff
@@ -303,4 +303,72 @@ class Command_Use_Lizard_Tests extends FunSuite {
...
+        val carGameMap = gameMap.asInstanceOf[CarGameMap]
+
+        val testGamePlayer1 = TestHelper.getTestGamePlayer1()
+        val testCarGamePlayer1 = testGamePlayer1.asInstanceOf[CarGamePlayer]
+        val testGamePlayer1Id = testCarGamePlayer1.getGamePlayerId()
+        testCarGamePlayer1.speed = Config.BOOST_SPEED
+        testCarGamePlayer1.pickupBoost()
+        testCarGamePlayer1.useBoost();
+        val newLaneMidRacePlayer1 = 2
+        val newBlockNumberMidRacePlayer1 = 67 // means end of round will be x = 38
```
Comment (KyleMcAllister) [inline game-engine/src/test/scala/Command_Use_Lizard_Tests.scala:352]: This comment is confusing

File: game-engine/src/test/scala/Command_Use_Lizard_Tests.scala [hunk 2]
```diff
@@ -303,4 +303,72 @@ class Command_Use_Lizard_Tests extends FunSuite {
...
+        TestHelper.putPlayerSomewhereOnTheTrack(carGameMap, testGamePlayer1Id, newLaneMidRacePlayer1, newBlockNumberMidRacePlayer1)
+
+        val testGamePlayer2 = TestHelper.getTestGamePlayer2()
+        val testCarGamePlayer2 = testGamePlayer2.asInstanceOf[CarGamePlayer]
+        val testGamePlayer2Id = testCarGamePlayer2.getGamePlayerId()
+        testCarGamePlayer2.speed = Config.MAXIMUM_SPEED // should be 9
+        testCarGamePlayer2.pickupLizard()
+        val newLaneMidRacePlayer2 = 2
+        val newBlockNumberMidRacePlayer2 = 68 // means end of round will be x = 38
```
Comment (KyleMcAllister) [inline game-engine/src/test/scala/Command_Use_Lizard_Tests.scala:361]: Same here
