### PR TITLE
Fix/player collision logic

### LINKED ISSUE #9: Parallel (same block) collision issue
It seems like the 'parallel' collision is not working as per the instructions. In the console log below, both bots would end up on block (y:2, x:12) which (as I understand from the instructions) should mean that Player1 should be (y:1, x:11) and Player2 (y:3, x:11), original lanes (y) and x-1. Instead it seems Player2 has been penalised and has not moved *at all*, still stuck on the original (y:3, x:7) block, whereas Player1 got his full move. Interestingly, both Players *did* receive the speed penalty: 6 down to 3, which could either be due to the actual collision or the fact that (y:2, x:12) is a MUD block.

The console log below as been altered slightly for readability, but all the important parts are still there:

```=======================================
Starting round: 2 
=======================================

player: id:1 position: y:1 x:7 speed:6 state:ACCELERATING ...
opponent: id:2 position: y:3 x:7 speed:6

[░░░░░1░░░░░░▓░░▓░░░▓░░░░░░]
[░░░░░░░░░░▓░░░░░░░░░▓░░▓░░]
[░░░░░2▓░░░░░░░▓░░▓░░░░░░░░]
[░░░░░░░░▓▓░░░░░░░»░░░░░░░░]
=======================================
C;2;TURN_RIGHT
C;2;TURN_LEFT
=======================================
Completed round: 2 
=======================================

=======================================
Starting round: 3 
=======================================

=======================================
round:3
player: id:1 position: y:2 x:12 speed:3 state:HIT_MUD ...
opponent: id:2 position: y:3 x:7 speed:3

[░░░░░░░▓░░▓░░░▓░░░░░░░░░░░]
[░░░░░1░░░░░░░░░▓░░▓░░░░░░░]
[2▓░░░░░░░▓░░▓░░░░░░░░░░»░░]
[░░░▓▓░░░░░░░»░░░░░░░░░▓░░░]
=======================================
C;3;TURN_RIGHT
C;3;TURN_LEFT
=======================================
Completed round: 3 
=======================================

### PR DESCRIPTION
**Pull request by KyleMcAllister**
0. Describe the correct collision behavior via tests
1. Stage future positions sequentially
2. Resolve (commit) future positions all at once (i.e. concurrently) applying collision rules
3. Apply other game logic after future positions are corrected for collisions

Closes #9

### CODE REVIEW

File: game-engine/src/main/scala/za/co/entelect/challenge/game/contracts/map/CarGameMap.scala [hunk 1]
```diff
@@ -189,4 +191,103 @@ class CarGameMap(players: util.List[Player], mapGenerationSeed: Int, lanes: Int,
...
+      (player2StagedPosition.getOldPosition().getBlockNumber() < player1StagedPosition.getOldPosition().getBlockNumber()) && //player 2 was behind
+      (player2FuturePosition.getBlockNumber() >= player1FuturePosition.getBlockNumber()) && //player 2 ended up in front
+      (player2FuturePosition.getLane() == player1FuturePosition.getLane()) //in the same lane => player 1 got ridden over
+
+    val isCollisionFromBehind = player1DroveIntoPlayer2 || player2DroveIntoPlayer1
+
+    val isCollision = playersFuturePositionsAreSame || isCollisionFromBehind
+
+    if(!isCollision)
+    {
```
Comment (Blaarkies) [inline game-engine/src/main/scala/za/co/entelect/challenge/game/contracts/map/CarGameMap.scala]: I think this brace belongs in c# code 😉

**Comment by ThePheonixGuy** [comment]
I'm also happy but have no power here unfortunately.

File: game-engine/src/main/scala/za/co/entelect/challenge/game/contracts/map/CarGameMap.scala [hunk 2]
```diff
@@ -189,4 +191,103 @@ class CarGameMap(players: util.List[Player], mapGenerationSeed: Int, lanes: Int,
...
+    val player1StagedPosition = stagedFuturePositions.find(x => x.getPlayer().getGamePlayerId() == 1).get
+    val player1FuturePosition = player1StagedPosition.getNewPosition()
+
+    val player2StagedPosition = stagedFuturePositions.find(x => x.getPlayer().getGamePlayerId() == 2).get
+    val player2FuturePosition = player2StagedPosition.getNewPosition()
+
+    val playersFuturePositionsAreSame = (player1FuturePosition.getLane() == player2FuturePosition.getLane()) && (player1FuturePosition.getBlockNumber() == player2FuturePosition.getBlockNumber())
+
+    val player1DroveIntoPlayer2 = (player1StagedPosition.getOldPosition().getLane() == player2StagedPosition.getOldPosition().getLane()) && //started off in the same lane
+      (player1StagedPosition.getOldPosition().getBlockNumber() < player2StagedPosition.getOldPosition().getBlockNumber()) && //player 1 was behind
```
Comment (ThePheonixGuy) [inline game-engine/src/main/scala/za/co/entelect/challenge/game/contracts/map/CarGameMap.scala]: You could extract these comparisons out to variables, removing the need for comments and making debugging this possible.

To prevent variable spam and variable duplication in this method, you could also extract the logic into a method that takes a LHS player and RHS player and returns LHSdroveIntoRHSPlayer Boolean. Makes this far more readable IMO, but unneeded in terms of functionality.

File: game-engine/src/main/scala/za/co/entelect/challenge/game/contracts/game/CarGameRoundProcessor.scala [hunk 3]
```diff
@@ -21,6 +21,9 @@ class CarGameRoundProcessor extends GameRoundProcessor{
       var playerCommand: RawCommand = commandFactory.makeCommand(commandText);
       playerCommand.performCommand(gameMap, gamePlayer);
     }
+
+    carGameMap.resolvePlayerCollisions();
+    carGameMap.commitStagedPositions();
```
Comment (ThePheonixGuy) [inline game-engine/src/main/scala/za/co/entelect/challenge/game/contracts/game/CarGameRoundProcessor.scala]: I really like this way of doing this.

File: game-engine/src/test/scala/ConcurrentLogic_Tests.scala [hunk 4]
```diff
@@ -0,0 +1,325 @@
...
+    val gameMap = TestHelper.initialiseGameWithNoMapObjects()
+    val carGameMap = gameMap.asInstanceOf[CarGameMap]
+
+    val testGamePlayer1 = TestHelper.getTestGamePlayer1()
+    val testCarGamePlayer1 = testGamePlayer1.asInstanceOf[CarGamePlayer]
+    val testGamePlayer1Id = testCarGamePlayer1.getGamePlayerId()
+    testCarGamePlayer1.speed = Config.SPEED_STATE_2 //should be 6
+    val newLaneMidRacePlayer1 = 2
+    val newBlockNumberMidRacePlayer1 = 35
+    TestHelper.putPlayerSomewhereOnTheTrack(carGameMap, testGamePlayer1Id, newLaneMidRacePlayer1, newBlockNumberMidRacePlayer1)
```
Comment (ThePheonixGuy) [inline game-engine/src/test/scala/ConcurrentLogic_Tests.scala]: All of the above could've been moved into setup methods, IMO.

File: game-engine/src/test/scala/ConcurrentLogic_Tests.scala [hunk 5]
```diff
@@ -0,0 +1,325 @@
...
+    val newLaneMidRacePlayer2 = 4
+    val newBlockNumberMidRacePlayer2 = 35
+    TestHelper.putPlayerSomewhereOnTheTrack(carGameMap, testGamePlayer2Id, newLaneMidRacePlayer2, newBlockNumberMidRacePlayer2)
+
+    //Act: process commands that would cause a collision
+    TestHelper.processRound(gameMap, turnRightCommand, turnLeftCommand)
+
+    //Assert: player positions have been corrected to resolve the collision
+    assert(testCarGamePlayer1.speed == Config.SPEED_STATE_1, "Player did not interact with map object on corrected path")
+  }
```
Comment (ThePheonixGuy) [inline game-engine/src/test/scala/ConcurrentLogic_Tests.scala]: Epic tests 👍

File: game-engine/src/main/scala/za/co/entelect/challenge/game/contracts/map/CarGameMap.scala (hunk 1 above)
Comment (KyleMcAllister) [reply game-engine/src/main/scala/za/co/entelect/challenge/game/contracts/map/CarGameMap.scala]: 😝 lol, my bad. Habits die hard

File: game-engine/src/main/scala/za/co/entelect/challenge/game/contracts/map/CarGameMap.scala (hunk 2 above)
Comment (KyleMcAllister) [reply game-engine/src/main/scala/za/co/entelect/challenge/game/contracts/map/CarGameMap.scala]: Will definitely add the variables (agree that if I was debugging this next week it would not be easy). Will try the LHS and RHS thing

File: game-engine/src/main/scala/za/co/entelect/challenge/game/contracts/game/CarGameRoundProcessor.scala (hunk 3 above)
Comment (KyleMcAllister) [reply game-engine/src/main/scala/za/co/entelect/challenge/game/contracts/game/CarGameRoundProcessor.scala]: Thanks 💃

File: game-engine/src/test/scala/ConcurrentLogic_Tests.scala (hunk 4 above)
Comment (KyleMcAllister) [reply game-engine/src/test/scala/ConcurrentLogic_Tests.scala]: Will give the tests another look to remove duplication 👍

File: game-engine/src/test/scala/ConcurrentLogic_Tests.scala (hunk 5 above)
Comment (KyleMcAllister) [reply game-engine/src/test/scala/ConcurrentLogic_Tests.scala]: Thanks 💃

File: game-engine/src/main/scala/za/co/entelect/challenge/game/contracts/map/CarGameMap.scala (hunk 1 above)
Comment (KyleMcAllister) [reply game-engine/src/main/scala/za/co/entelect/challenge/game/contracts/map/CarGameMap.scala]: Will boy-scout as I go along 👍 and fix this one
